version: "2.2"
services:
  pgdatabase:
    image: 'postgres:13'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
<<<<<<< HEAD
      - "./data/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
=======
      - './ny_taxi_postgres_data:/var/lib/postgresql/data:rw'
>>>>>>> 7309b9894799a01b8674dd95a9eae3c2e4f1408a
    ports:
      - '5432:5432'
  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '8080:80'
